from prompts import HELPFUL_ASSISTANT


MODEL = "gpt-4.1-mini"
TEMPERATURE = 0.3

SYSTEM_PROMPT = HELPFUL_ASSISTANT

INPUT_PRICE_PER_MILLION = 1.00
OUTPUT_PRICE_PER_MILLION = 2.00

MAX_CONTEXT_TOKENS = 4000

SUMMARY_TRIGGER_TOKENS = 1500